# Generated by Django 4.0 on 2021-12-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='дата публикации')),
                ('text', models.TextField(verbose_name='описание')),
                ('price', models.IntegerField(verbose_name='стоимость')),
                ('photo', models.ImageField(upload_to='images', verbose_name='изображение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.user', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
    ]
